sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "CIsBMNaaKjR/g4/vlvtDRDqB2pf7azUWqfTZaJO5CRmRCDV4n4AI8CkNPvGVcFpHoGvzDYX0MeBMi/cJVixWaj36fa0FQiI5iSJX2PkrLXh/EDRIMNmHd9vii/OrK0O+DAd6si3vCovioh+LpHKV3SIjzHCdQsO2Llxmplqdp92tljg9s5wKNsO5+MAnGwg+Or2j150z6Vf6jXwxNiKBJQR5crJsMUaWERFsvuqpIcmYyRATFedczf9CeM4uwGeL/2YbK5PTULb8/YhzUGtei9Y85UN21r8I4ANofD7OqDi4+hhEYD515mIsjGUVztie7N3pQvjAd/r1kZHy+I2YxmYHwpbRn2aadBm8MWStZpAZU/LDXKR0l2TZYG5nx2z77B73sBPi/7T/JGeaalxAtLSnSe0720KVDcABfWXKGP/mt3bdR5BB/nuDKOarZRpTYQo8Lpvxo2cq8ob94n81Pz6Q749LgteNvaz0bOLrDg180Fex2+Q67jEgkJOa+MY3vHJExoHiI5z7XTUBwAND5U4epwUE5hCmHUYklBO0DdTxNH/RV9NwAg8uIwd1LSeTIwmXhSJdWZdX9rmpVt/KW5AZ6KatQKK98NSubHjiNjFuBXV60PNiyD/mqGrm1qy136N0SfgCaW+FR8/W82mQ/l93OuDWhvIubCBP/GqgMBQ="
  - secure: "EJeJIF1nt9csX2Z0lRKmBabehiLJYMEyfpGvGqxmGvhv4Ef0Jk6ni8RzzgrWqlOscYRCCKPpk3KSoGt+gs4/RpdvmRYAvv7iShBdJF1s1qkLhP4tHpkYiPBrVHjeIlz7Tj4s+WPgbBGV2sHSSqEFRPFg+snBW85RUAV2aS8vrzH4+ROZrp1HrDmk5THu7oPXvIy1wEm6Ya3N+hRSsYjBPCky4hOwSzzN1tkE7vXwb4L2Hd2TbLDZpWGiHiulvf2lNsh3VoNgUe6V2Sp0zpfXpo1Mv5gFb/DokDmnpwWQTlDOHPSD2G46n/vPYpTE+O1KrnBHeYuRhRuWxwgShd0j7pAgob2pq151sxaFSQTESQrto0u2X1pn0A5Z5NKb0Pae+L7l+u76JoA+9swtPlCsv81l31wGfNKP/vBPEE33wnmYcXpiI8Hke0TeBuJkEI+lTT0M45CGHbJEEyd9xMIoAbGUAMMIrz2X5sCLaCLQSi0C4mcgp5NGMaXevoSHqamoystLKstVaND7GUG/KH8Cwwly/d1p8XbGC97dztQtYTsWgxFCgyfVS6irGi37k1j2661+nhAa4E9grXIIupPaq9DinjcLVKBu/mj+CFAswu+ul/s/fEo1a6Pm5bve/DQNtw4Dyqmh/V5Zbd4PIyikzkkaNvtSNV9AAGm4+XA+sN8="
  - secure: "fiV+kbdXKgMBPlSgOjWlHf4l3CErHZBe7ZxTQdD65zq/5Y3HMTIHtqYs56fjkYgWh0ztOvJ6DLtHAHztNTI25l6h1KOwLLDOCvu0AXTFcw/zjnFnCLUZBmFiADfK7/7tGVetQ3g0G2Rzxl+JY+X6VIVA1NOWc8xvVmHn0MDnIaiDWmCWboHR0A9FujgeWnUHr99o0aRg4qzJNGczauSgLWIGnrsMgqyfUlCuI3H/yMCm6g7WzBpGKRMShI5MoZf8elelDXbDUJ/m32mo1xwtLnAy1EM46O2KUrrzbKKORyOuPDWM02lR6361bqlIeo1QDQr5vECk9KWmBE19tQx4984MBJaPiBoV4BlzIZJ0TONpbMOakN2VXuTyEDBe2foIT5V2QWPikQQ2HOkLyvm4yvwH3XKVpW2Ma7DibjBgPzDdPBI1rr9nF+h73fsRv/YGlhu7S5BqcuVrrGp5gHjq7NC842LNmOcclzKhxcRmJEIlxUj9nqPXW+SKUVzj0bHTm5y2ODrPX7pNeV1OxMuJJoG+iHcCf4185Cb/vpvD/jiDsYHPNM/D96OxCfw8ctfvN+Klk+3BwqHR9Ol1OnbhmZnEMPEdYTpzPUmoMy2kasQyUWDNLVbLFn1YuqehPJKcJ3LSBpkxncjpmcRTcfqlaL7oWohkP+qnUNva+/LQBog="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
